version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels: ["dependencies", "github-actions"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    labels: ["dependencies", "docker"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/src/dashboard"
    schedule:
      interval: monthly
    labels: ["dependencies", "typescript"]
    open-pull-requests-limit: 5
